### ISSUE TITLE
Please restart the script of '伏安特性'

### ISSUE THREAD

**Issue by winderica** [recolic/phy-exp#1]
Thank you for your effort, and I had to apologize that the script crashed because of my invalid input by mistake :(
I will be extremely grateful if you can relaunch it as soon as possible.

**Comment by recolic** [comment]
could you please attach any crash log and your input? This project is not well-maintained because I'm just sharing my code to save other's time. tks)

**Comment by recolic** [comment]
Please wait for my fix ..... This project is not well-maintained because I'm just sharing my code to save other pythoners' time.

**Comment by winderica** [comment]
Thank you, looking forward to your fix 👍

**Comment by recolic** [comment]
Fixed.

**Comment by winderica** [comment]
still doesn't work:
### way to reproduce
- input random data in the **second** part of '伏安特性'
- then you will find the browser crashed
### what I have done
- clear the cache of browser (incognito tab)
- adopt a better network environment

> sorry for unable to provide the errors in f12 console because I am using chrome mobile now.

**Comment by recolic** [comment]
emmmmm.........You're talking about `recolic.net/phy` ? It's not a part of this repo.
I'm the author of `scripts` rather than `webpages`. It's written by xuezhaquan.xyz, so I can't provide further help... 
If anyone is willing to fix the bug, I'm happy to update it.

**Comment by recolic** [comment]
besides, you're free to use chinese if preferred

**Comment by winderica** [comment]
谢谢告知，那个网站是正常的，但是你的镜像站点还是会崩溃（页面卡死，控制台没有任何报错）。说明不是后端代码的问题，可能是你的服务器炸了？
~（之前用英语其实是想维护社区的环境~
打扰了.jpg
